# application.properties

ruta.txt=src/main/resources/empleados.txt
ruta.csv=src/main/resources/empleados.csv
ruta.xlsx=src/main/resources/empleados.xlsx
ruta.xml=src/main/resources/empleados.xml
ruta.json=src/main/resources/empleados.json
